replicaCount: 2

image:
  repository: guyhagever/cloudpulse
  tag: "6363e9f17f78985b89c14392b5cfe1e9529f7120"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: cloudpulse.local

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
