apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudpulse-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/guyhagever/cloudpulse-gitops.git
    targetRevision: main
    path: helm/cloudpulse
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudpulse-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
